# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import note.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No name', max_length=200)),
                ('file', models.FileField(upload_to=note.models.content_file_name)),
                ('preview', models.ImageField(blank=True, null=True, upload_to=note.models.preview_file_name)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='note.Categories')),
            ],
            options={
                'verbose_name': 'Category',
                'db_table': 'categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Color',
                'db_table': 'colors',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Label',
                'db_table': 'labels',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_editing', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('category', models.ManyToManyField(blank=True, default=None, related_name='categories', to='note.Categories')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colors', to='note.Colors')),
                ('delegated', models.ManyToManyField(blank=True, related_name='users_allow', to=settings.AUTH_USER_MODEL)),
                ('file', models.ManyToManyField(blank=True, related_name='attach', to='note.Attachments')),
                ('label', models.ManyToManyField(blank=True, related_name='labels', to='note.Labels')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'db_table': 'notes',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
