# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:26
from __future__ import unicode_literals

from django.db import migrations

from os import path


def load_colors(apps, schema_editor):
    color = apps.get_model("note", "Colors")
    colors = []
    with open(path.join(path.dirname(__file__), 'colors.txt')) as f:
        for line in f.readlines():
            colors.append(color(color=line.strip()))
    color.objects.bulk_create(colors)


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_colors)
    ]
