# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:42
from __future__ import unicode_literals

from django.db import migrations

from os import path


def load_labels(apps, schema_editor):
    color = apps.get_model("note", "Labels")
    colors = []
    with open(path.join(path.dirname(__file__), 'labels.txt')) as f:
        for line in f.readlines():
            colors.append(color(title=line.strip()))
    color.objects.bulk_create(colors)


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20160425_0826'),
    ]

    operations = [
        migrations.RunPython(load_labels)
    ]
